addrdb: fix include dependency and remove redefined
Currently I get this compile error:

coord-config-parse.h:106:14: error: unknown type name 'yyscan_t'
coord-config-parse.y:38:0: error: "YYDEBUG" redefined [-Werror]

"yyscan_t" is defined in parser.h but parser.h need a include from
coord-config-parse.h for "YYSTYPE".

This patch removes typedef of "yyscan_t" from parser.h into new
file scanner.h.

File coord-config-parse.y includes scanner.h at first so "yyscan_t"
is known.

Remove redefined:
Move #define YYDEBUG 1 in coord-config-parse.y at first. Otherwise
it will be defined in generated coord-config-parse.h to 0.

Tested with bison (GNU Bison) 2.7.

Signed-off-by: Alexander Aring <alex.aring@gmail.com>