build: check for libnl-genl which is a separate library
The detection for extra libs fails in my environment. According to
config.log:

configure:12586: checking whether libnl requires additional libraries
configure:12608: gcc -o conftest -g -O2   conftest.c -lnl-3    >&5
/tmp/ccfZXCbJ.o: In function `main':
/home/jengelh/obs/zu/home/jengelh/dev/lowpan-tools/lowpan-tools/
 conftest.c:35: undefined reference to `genl_connect'
collect2: ld returned 1 exit status

This happens because lowpan-tools forgot that genl_connect is in its
own library in libnl2 and up. Furthermore, any dependent libraries of
libnl* is listed in the .so, or in case of static archives, .la files,
rendering the -lm check redundant.

Signed-off-by: Jan Engelhardt <jengelh@inai.de>